currLabel: Assets
customIcon: null
enabled: false
handle: assets
icon: image
layout: 988daa59-41c8-40fa-8bbf-11a8de9a22e4 # Providers
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 4
type: craft
url: assets
