currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: sitemap
layout: 609ed43b-16c2-4f85-8eff-930ee20cb533 # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: 1
prevParent: null
prevUrl: categories
sortOrder: 3
type: craft
url: categories
