currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: newspaper
layout: 988daa59-41c8-40fa-8bbf-11a8de9a22e4 # Providers
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
type: craft
url: entries
