currLabel: GraphiQL
customIcon: null
enabled: true
handle: graphiql
icon: null
layout: 609ed43b-16c2-4f85-8eff-930ee20cb533 # Default
level: 2
newWindow: true
parent: 826fb4c4-cdf0-4697-a7ba-ec528f5a3dde
prevLabel: GraphiQL
prevLevel: 2
prevParent: 826fb4c4-cdf0-4697-a7ba-ec528f5a3dde
prevUrl: graphiql
sortOrder: 15
type: craft
url: graphiql
