defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a2586b7e-9bb3-43af-bd80-784c8d064e9d # Content Page
  -
    uid: 85aaa7b4-1813-45d7-847f-28151be7e7b4 # Directory listing
handle: pages
maxAuthors: null
name: Pages
propagationMethod: all
siteSettings:
  0e198a9f-3b1b-487f-80ee-3c2aeed6d349: # DBT Search
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.uri}/{entry.slug}'
structure:
  maxLevels: 1
  uid: bd86e753-8d68-45ea-87e2-0d31847956a5 # Pages structure
type: structure
