defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3581a892-e035-42ec-9cd0-7843ee2a87d6 # Provider
handle: providers
maxAuthors: 1
name: Providers
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  0e198a9f-3b1b-487f-80ee-3c2aeed6d349: # DBT Search
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
