columnSuffix: null
handle: useDarkBackgroundForLogo
instructions: null
name: 'Use dark background for logo'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
