dateModified: 1775618725
email:
  fromEmail: system@dbtsearch.org
  fromName: 'DBT Search'
  replyToEmail: no-reply@dbtsearch.org
  template: null
  transportSettings:
    apiKey: $RESEND_API_KEY
  transportType: superbig\resend\Adapter
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: $CRAFT_WEB_ROOT/uploads
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/uploads
meta:
  __names__:
    0e198a9f-3b1b-487f-80ee-3c2aeed6d349: 'DBT Search' # DBT Search
    1f048049-d0c9-4364-8a8d-736b4d508537: Pending # Pending
    68f6aaed-7edc-4e91-9996-3a86c16baf2f: 'Basic Editor' # Basic Editor
    98fab9df-c419-4085-9a57-5c61f96573c2: Form # Form
    288c542e-3541-4e24-96ee-aa5fa0bea135: General # General
    3220f3b5-89ff-450e-9a8c-83bd4b04bdf5: 'Public Schema' # Public Schema
    acef0518-5cc6-4dd0-9231-234846cfc200: Approved # Approved
    bcf50025-2188-4126-a360-29999caeae89: 'Splash Page' # Splash Page
    cc0c373f-6532-483b-831f-3c8878b9bb8e: 'DBT Search' # DBT Search
    d7cbe0ad-28b6-4a03-ace9-d634d2072400: 'Contact Form' # Contact Form
    ddb25fd5-a759-494a-9d4d-96a6e44c941e: 'Plain Text' # Plain Text
    ddb17090-e3f7-41d7-aab7-b1729da37d11: Subscriber # Subscriber
    e37b7064-6cc1-44c5-a156-52caa30e8b65: 'Splash Page' # Splash Page
    eb8a7a70-63cb-4cc1-bae4-e3516a6766ee: Splash # Splash
    fe417a71-4d1b-460f-8a63-7ac81c0e5092: Images # Images
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.0.0.1
  formie:
    edition: standard
    enabled: true
    licenseKey: QUKB6ZEKL37AO89B4TEAAZKZ
    schemaVersion: 3.4.12
    settings:
      ajaxTimeout: 10
      alertEmails:
        -
          - 'Brian Larson'
          - brian@brianlarson.com
      allowPublicVolumes: true
      defaultDateDisplayType: calendar
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultExportFolder: '@storage/formie-export'
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      emptyValuePlaceholder: 'No response.'
      enableBackSubmission: true
      enableCsrfValidationForGuests: true
      enableLargeFieldStorage: false
      enableUnloadWarning: true
      filterIntegrationMapping: true
      includeDraftElementUsage: false
      includeRevisionElementUsage: false
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      outputConsoleMessages: true
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pluginName: Forms
      queuePriority: null
      saveSpam: true
      sendEmailAlerts: true
      sentNotifications: true
      setOnlyCurrentPagePayload: false
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: true
      spamKeywords: ''
      spamLimit: 500
      submissionsBehaviour: all
      useCssLayers: false
      useQueueForIntegrations: true
      useQueueForNotifications: true
      validateCustomTemplates: true
  resend:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: team
  live: true
  name: 'DBT Search'
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
